name: flexisuite_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.8
  intl: ^0.20.2
  file_picker: ^10.3.3
  flexisuite_shared:
    path: ../flexisuite_shared
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.10.0
  url_launcher: ^6.1.10
  provider: ^6.1.2
  share_plus: ^12.0.0 # Para compartir archivos y texto
  path_provider: ^2.1.3 # Para obtener rutas de directorios temporales
  shared_preferences: ^2.2.3
  timezone: ^0.10.1 # Para manejo de zonas horarias
  flutter_native_timezone: ^2.0.0 # Para obtener la zona horaria nativa
  fluttertoast: ^8.2.6 # Para notificaciones tipo "toast"
  csv: ^6.0.0 # Para parsear archivos CSV
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  table_calendar: ^3.2.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/favicon.png"
  remove_alpha_ios: true # Añadimos esta línea para forzar la regeneración.

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - web/favicon.png
    - assets/logo_login.png # Añadimos el nuevo logo a los assets.
